"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CONSENT_STATUS_ACCEPTED = exports.CONSENT_STATUS_NOT_ACCEPTED = void 0;
var CONSENT_STATUS_NOT_ACCEPTED = 'NOT_ACCEPTED';
exports.CONSENT_STATUS_NOT_ACCEPTED = CONSENT_STATUS_NOT_ACCEPTED;
var CONSENT_STATUS_ACCEPTED = 'ACCEPTED';
exports.CONSENT_STATUS_ACCEPTED = CONSENT_STATUS_ACCEPTED;