"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.VENDOR_CONSENT_COOKIE_DEFAULT_PATH = exports.VENDOR_CONSENT_COOKIE_MAX_AGE = exports.VENDOR_CONSENT_COOKIE_NAME = void 0;
var VENDOR_CONSENT_COOKIE_NAME = 'euconsent';
exports.VENDOR_CONSENT_COOKIE_NAME = VENDOR_CONSENT_COOKIE_NAME;
var VENDOR_CONSENT_COOKIE_MAX_AGE = 33696000;
exports.VENDOR_CONSENT_COOKIE_MAX_AGE = VENDOR_CONSENT_COOKIE_MAX_AGE;
var VENDOR_CONSENT_COOKIE_DEFAULT_PATH = '/';
exports.VENDOR_CONSENT_COOKIE_DEFAULT_PATH = VENDOR_CONSENT_COOKIE_DEFAULT_PATH;