"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_NEW_VENDORS_STATUS_OPTION = exports.DEFAULT_DEBUG_KEYWORD = exports.DEFAULT_VENDOR_LIST_FILENAME = exports.DEFAULT_VENDOR_LIST_HOST = exports.DEFAULT_GDPR_STORE_CONSENT_GLOBALLY = exports.DEFAULT_GDPR_APPLIES = exports.DEFAULT_LOG_LEVEL = exports.DEFAULT_CONSENT_LANGUAGE = exports.DEFAULT_CONSENT_SCREEN = void 0;

var _Log = require("../service/log/Log");

var _NewVendorsStatusService = require("../../domain/vendor_consents/NewVendorsStatusService");

var DEFAULT_CONSENT_SCREEN = 1;
exports.DEFAULT_CONSENT_SCREEN = DEFAULT_CONSENT_SCREEN;
var DEFAULT_CONSENT_LANGUAGE = 'es';
exports.DEFAULT_CONSENT_LANGUAGE = DEFAULT_CONSENT_LANGUAGE;
var DEFAULT_LOG_LEVEL = _Log.LEVEL.warn;
exports.DEFAULT_LOG_LEVEL = DEFAULT_LOG_LEVEL;
var DEFAULT_GDPR_APPLIES = true;
exports.DEFAULT_GDPR_APPLIES = DEFAULT_GDPR_APPLIES;
var DEFAULT_GDPR_STORE_CONSENT_GLOBALLY = false;
exports.DEFAULT_GDPR_STORE_CONSENT_GLOBALLY = DEFAULT_GDPR_STORE_CONSENT_GLOBALLY;
var DEFAULT_VENDOR_LIST_HOST = 'https://vendorlist.consensu.org';
exports.DEFAULT_VENDOR_LIST_HOST = DEFAULT_VENDOR_LIST_HOST;
var DEFAULT_VENDOR_LIST_FILENAME = 'vendorlist.json';
exports.DEFAULT_VENDOR_LIST_FILENAME = DEFAULT_VENDOR_LIST_FILENAME;
var DEFAULT_DEBUG_KEYWORD = 'cmp_debug';
exports.DEFAULT_DEBUG_KEYWORD = DEFAULT_DEBUG_KEYWORD;
var DEFAULT_NEW_VENDORS_STATUS_OPTION = _NewVendorsStatusService.OPTION_USE_SAME_THAN_ALL_CUSTOM_IS_TRUE;
exports.DEFAULT_NEW_VENDORS_STATUS_OPTION = DEFAULT_NEW_VENDORS_STATUS_OPTION;