"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.WRITE_CONSENT_COMMAND = exports.READ_CONSENT_COMMAND = void 0;
var READ_CONSENT_COMMAND = 'READ_CONSENT_COMMAND';
exports.READ_CONSENT_COMMAND = READ_CONSENT_COMMAND;
var WRITE_CONSENT_COMMAND = 'WRITE_CONSENT_COMMAND';
exports.WRITE_CONSENT_COMMAND = WRITE_CONSENT_COMMAND;