"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.POST_MESSAGE_DEFAULT_REQUEST_TIMEOUT = exports.POST_MESSAGE_TARGET_ORIGIN = exports.POST_MESSAGE_ID = void 0;
var POST_MESSAGE_ID = 'message';
exports.POST_MESSAGE_ID = POST_MESSAGE_ID;
var POST_MESSAGE_TARGET_ORIGIN = '*';
exports.POST_MESSAGE_TARGET_ORIGIN = POST_MESSAGE_TARGET_ORIGIN;
var POST_MESSAGE_DEFAULT_REQUEST_TIMEOUT = 200;
exports.POST_MESSAGE_DEFAULT_REQUEST_TIMEOUT = POST_MESSAGE_DEFAULT_REQUEST_TIMEOUT;